org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# https://modmuss50.me/fabric.html
minecraft_versions=26.3
minecraft_version=26.3
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
java_version=25
# Fabric API
fabric_api_version=0.161.0+26.3
# Mod Properties
mod_id=linkart
mod_name=Linkart Overhaul
mod_version=6.3.6
mod_release_type=release
maven_group=com.darkgreen_world
